### ISSUE TITLE
Cannot find module 'cuss/index.json'.

### ISSUE THREAD

**Issue by onukselcuk** [cityssm/simple-password-generator#153]
A lot of problems occur after the installation of the latest release.

TS2732: Cannot find module 'cuss/index.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
    3 | import { generatePasswordFromPattern } from "./passwordGenerator";
    4 | import { unleet } from "@cityssm/unleet";
  > 5 | import * as cussWordsObject from "cuss/index.json";
      |                                  ^^^^^^^^^^^^^^^^^
    6 |
    7 |
    8 | /*

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:46:1
TS2322: Type 'null' is not assignable to type 'string[]'.
    44 | });
    45 |
  > 46 | cussWordsUnfiltered = null;
       | ^^^^^^^^^^^^^^^^^^^
    47 |
    48 |
    49 | const _hasCussWord = (unleetedString: string) => {

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:90:39
TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
    88 |   const generateOptions = Object.assign({}, defaultGenerateOptions, userGenerateOptions);
    89 |
  > 90 |   generateOptions.minScore = Math.min(generateOptions.minScore, 4);
       |                                       ^^^^^^^^^^^^^^^^^^^^^^^^
    91 |
    92 |   let passwordPattern = generateOptions.pattern;
    93 |

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:96:37
TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    94 |   // Shuffle the pattern if necessary
    95 |   if (generateOptions.doShufflePattern) {
  > 96 |     passwordPattern = shuffleString(passwordPattern);
       |                                     ^^^^^^^^^^^^^^^
    97 |   }
    98 |
    99 |   let retries = generateOptions.retries;

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:102:10
TS2532: Object is possibly 'undefined'.
    100 |
    101 |   // Loop through retries
  > 102 |   while (retries > 0) {
        |          ^^^^^^^
    103 |
    104 |     const potentialPassword = generatePasswordFromPattern(passwordPattern);
    105 |

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:104:59
TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    102 |   while (retries > 0) {
    103 |
  > 104 |     const potentialPassword = generatePasswordFromPattern(passwordPattern);
        |                                                           ^^^^^^^^^^^^^^^
    105 |
    106 |     // Check length, check for potential cuss words
    107 |     if (potentialPassword.length >= generateOptions.minLength &&

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:107:37
TS2532: Object is possibly 'undefined'.
    105 |
    106 |     // Check length, check for potential cuss words
  > 107 |     if (potentialPassword.length >= generateOptions.minLength &&
        |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
    108 |       potentialPassword.length <= generateOptions.maxLength &&
    109 |       zxcvbn(potentialPassword).score >= generateOptions.minScore &&
    110 |       !hasCussWord(potentialPassword)) {

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:108:35
TS2532: Object is possibly 'undefined'.
    106 |     // Check length, check for potential cuss words
    107 |     if (potentialPassword.length >= generateOptions.minLength &&
  > 108 |       potentialPassword.length <= generateOptions.maxLength &&
        |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    109 |       zxcvbn(potentialPassword).score >= generateOptions.minScore &&
    110 |       !hasCussWord(potentialPassword)) {
    111 |

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:109:7
TS2349: This expression is not callable.
  Type '{ default: (password: string, userInputs?: string[] | undefined) => ZXCVBNResult; }' has no call signatures.
    107 |     if (potentialPassword.length >= generateOptions.minLength &&
    108 |       potentialPassword.length <= generateOptions.maxLength &&
  > 109 |       zxcvbn(potentialPassword).score >= generateOptions.minScore &&
        |       ^^^^^^
    110 |       !hasCussWord(potentialPassword)) {
    111 |
    112 |       return potentialPassword;

ERROR in node_modules/@cityssm/simple-password-generator/index.ts:115:5
TS2532: Object is possibly 'undefined'.
    113 |     }
    114 |
  > 115 |     retries -= 1;
        |     ^^^^^^^
    116 |   }
    117 |
    118 |   return null;

**Comment by dangowans** [comment]
Looking into this now.

**Comment by dangowans** [comment]
> TS2732: Cannot find module 'cuss/index.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

How are you getting the simple-password-generator package?  From npm?

If you are attempting to modify or recompile the TypeScript, you should probably download the full release from [the Releases section](https://github.com/cityssm/simple-password-generator/releases) here on GitHub.  The npm package does not contain the `tsconfig.json` file that has the `resolveJsonModule` option set.

**Comment by onukselcuk** [comment]
I'm getting it from npm and not trying to modify it. I turned off the first error with adding resolveJsonModule option to true. But rest of the errors stayed the same. If you can fix typescript errors I would really appreciate it.

**Comment by dangowans** [comment]
I must have looser TypeScript settings because I don't get the "Possibly undefined" warnings myself, but I tried to reduce some of them in v1.1.4.  It's now up on npm.

**Comment by onukselcuk** [comment]
Thank you
All errors are gone except one

TS2349: This expression is not callable.
  Type '{ default: (password: string, userInputs?: string[] | undefined) => ZXCVBNResult; }' has no call signatures.
    103 |     if (potentialPassword.length >= generateOptions.minLength &&
    104 |       potentialPassword.length <= generateOptions.maxLength &&
  > 105 |       zxcvbn(potentialPassword).score >= generateOptions.minScore &&
        |       ^^^^^^
    106 |       !hasCussWord(potentialPassword)) {
    107 |
    108 |       return potentialPassword;

**Comment by dangowans** [comment]
I made an attempt to correct the warning you are seeing in v1.1.5, now on npm.

If it doesn't pass your tests, I'm going to guess it will have something to do with the zxcvbn package, or more likely with the @types/zxcvbn package, which is a dev dependency, and may not be available.

**Comment by onukselcuk** [comment]
This is the new error. The other error is gone.

TS1202: Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
     6 | import type * as types from "./types";
     7 |
  >  8 | import zxcvbn = require("zxcvbn");
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     9 |
    10 |
    11 | /*

**Comment by dangowans** [comment]
That's what I had before.  I reverted the change in v1.1.6.  If the call signature warning returns, you may need to install @types/zxcvbn as a dev dependency.

**Comment by dangowans** [comment]
Going to close this issue.  If there's still something I can do to help, let me know.
